# DEFAULT SETTING
server:
  port: 8070
# FOR CONFIG SERVER
spring:
  application:
    # SAME NAME AS THE PROFILE PROPERTIES FILE
    # IN THE GIT REP OR CONFIG SERVER (e.g. eureka.yml)
    # (See Git Repo https://github.com/PierreSQS/eazybytes-config)
    name: "eurekaserver"

  # CONNECTION TO CONFIGSERVER
  config:
    import: "optional:configserver:http://localhost:8071/"

  # ENABLE COLOR ON TERMINAL ENTRIES
  output:
    ansi:
      enabled: ALWAYS

# ENABLING ACTUATORS PATH LIKE REFRESH PATH
# TO READ CHANGED PROPERTIES AT RUNTIME
# WITHOUT RESTARTING THE MicroSERVICES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # LIVENESS AND READINESS otherwise
  # HEALTHCHECK WILL NOT WORK
  # (See docker-compose file in docker-compose folder)
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  # GROUP THE MICROSERVICE METRICS UNDER
  # THE SAME APPLICATION NAME
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  # LOGGING PATTERN FOR OPEN TELEMETRY (Tracing)
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"