server:
  port: 9010

spring:
  application:
    name: "message"

  # COMPOSE FUNCTIONS IN MessageFunctions TOGETHER
  cloud:
    function:
      definition: email|sms
    # STREAM AND BINDING STUFF FOR RABBITMQ
    stream:
      bindings:
        # INPUT EXCHANGE
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        # OUTPUT EXCHANGE
        emailsms-out-0:
          destination: communication-sent

      # LINK TO KAFKA
      kafka:
        binder:
          brokers:
            - localhost:9092