spring:
  application:
    name: "ConfigServerPierrot"
  # ACTIVATE GIT PROFILE
  # FOR ACTIVATING GIT STORAGE OF CONFIG FILES
  profiles:
    #active: native
    active: git

  # GIT LOCATION OF THE µSERVICES CONFIGS
  cloud:
    config:
      server:
        #native:
        #  searchLocations: "classpath:/config/"
        git:
          #uri: "https://github.com/eazybytes/eazybytes-config.git"
          uri: "https://github.com/PierreSQS/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  # CONNECTION TO RabbitMQ OPTIONAL SINCE DEFAULT IN SPRING CLOUD BUS
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  output:
    ansi:
      enabled: ALWAYS

# ENABLING ACTUATORS PATH LIKE REFRESH PATH
# TO READ CHANGED PROPERTIES AT RUNTIME
# WITHOUT RESTARTING THE µSERVICES
management:
  endpoints:
    web:
      exposure:
        include: "*"

# FOR ENCRYPTING accounts.contactDetails.email"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071