spring:
  application:
    name: "ConfigServerPierrot"
  # ACTIVATE GIT PROFILE
  # FOR ACTIVATING GIT STORAGE OF CONFIG FILES
  profiles:
    #active: native
    active: git

  # GIT LOCATION OF THE µSERVICES CONFIGS
  cloud:
    config:
      server:
        #native:
        #  searchLocations: "classpath:/config/"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8071