server:
  port: 8090
# FOR CONFIG SERVER
spring:
  application:
    # SAME NAME AS THE PROFILE PROPERTIES FILE
    # IN THE GIT REP OR CONFIG SERVER (e.g. loans*.yml)
    # (See Git Repo https://github.com/PierreSQS/eazybytes-config)
    name: "loans"

  # ACTIVATE DEFAULT PROFILE
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # CONNECTION TO CONFIGSERVER
  config:
    import: "optional:configserver:http://localhost:8071/"

  # ENABLE COLOR ON TERMINAL ENTRIES
  output:
    ansi:
      enabled: ALWAYS

# ENABLING ACTUATORS PATH LIKE REFRESH PATH
# TO READ CHANGED PROPERTIES AT RUNTIME
# WITHOUT RESTARTING THE MicroSERVICES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  
  # ENABLE SHUTDOWN ENDPOINT URL
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  
  # ENABLE INFO RELATED URL
  info:
    env:
      enabled: true
  # GROUP THE MICROSERVICE METRICS UNDER
  # THE SAME APPLICATION NAME
  metrics:
    tags:
      application: ${spring.application.name}

# EXPOSE THE SHUTDOWN REST APIS
endpoints:
  shutdown:
    enabled: true

# CONNECTION TO EUREKA SERVER
eureka:
  instance:
    # SINCE NO DNS, PREFER IpAddress
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# APP INFOS FOR THE ACTUATOR
info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

# LOANS PACKAGE LOGGING
logging:
  level:
    com:
      eazybytes:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"