# Default values for dev-env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  configMapName: eazybankqa-configmap
  activeProfile: qa
  configServerURL: configserver:http://configserver-service:8071/
  discoveryServerURL: http://spring-cloud-kubernetes-discoveryserver:80
  keyCloakURL: http://keycloak2303.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.28.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka361-controller-0.kafka361-controller-headless.default.svc.cluster.local:9092