global:
  scrape_interval:     5s # Fetch the metrics every 5 seconds.
  evaluation_interval: 5s # Evaluate the metrics every 5 seconds.

# SERVICES TO MONITOR (E.G. GET THE METRICS FROM)
scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # ACCESS THE INSTANCE WITH THE NETWORK SERVICE NAME
      # SINCE WE ARE ACCESSING THE INSTANCE FROM DOCKER
      - targets: [ 'accounts:8080' ]
  - job_name: 'loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'loans:8090' ]
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards:9000' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
  
