services:
  accountsdb:
    image: mysql:8.0.35
    container_name: accountsdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: Galerien3?
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    image: mysql:8.0.35
    container_name: loansdb
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: Galerien3?
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  cardsdb:
    image: mysql:8.0.35
    container_name: cardsdb
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: Galerien3?
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "pierrotadesso/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "pierrotadesso/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "pierrotadesso/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "pierrotadesso/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"